# Generated by Django 5.2.6 on 2025-10-03 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('mssql', 'SQL Server')], max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('database', models.CharField(max_length=255)),
                ('schema', models.CharField(blank=True, max_length=255, null=True)),
                ('mongodb_connection_type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('atlas', 'Atlas')], default='standard', max_length=20)),
                ('atlas_connection_string', models.TextField(blank=True, null=True)),
                ('_username', models.TextField(db_column='username')),
                ('_password', models.TextField(db_column='password')),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('connection_options', models.JSONField(blank=True, default=dict)),
                ('pool_size', models.IntegerField(default=5)),
                ('max_overflow', models.IntegerField(default=10)),
                ('pool_timeout', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('active', 'Active'), ('failed', 'Failed'), ('unchecked', 'Not Tested')], default='unchecked', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('cached_schema', models.JSONField(blank=True, default=dict)),
                ('schema_updated_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('response_time_ms', models.IntegerField()),
                ('test_query', models.TextField()),
                ('server_info', models.JSONField(blank=True, default=dict)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_logs', to='databases.databaseconnection')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
