# Generated by Django 5.2.6 on 2025-09-23 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_url', models.URLField()),
                ('endpoint_path', models.CharField(max_length=500)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('oauth', 'OAuth 2.0')], default='none', max_length=20)),
                ('auth_credentials', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('body_schema', models.JSONField(blank=True, default=dict)),
                ('expected_response_format', models.CharField(default='json', max_length=20)),
                ('response_schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APITestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('request_headers', models.JSONField(default=dict)),
                ('request_params', models.JSONField(default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict, null=True)),
                ('response_status', models.IntegerField()),
                ('response_headers', models.JSONField(default=dict)),
                ('response_body', models.JSONField(blank=True, default=dict, null=True)),
                ('response_time_ms', models.IntegerField()),
                ('is_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('api_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_logs', to='apis.apiendpoint')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
