# Generated by Django 5.2.6 on 2025-09-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='body_template',
            field=models.JSONField(blank=True, default=dict, help_text='Template for request body'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='content_type',
            field=models.CharField(choices=[('application/json', 'JSON'), ('application/x-www-form-urlencoded', 'Form Data'), ('multipart/form-data', 'Multipart'), ('application/xml', 'XML')], default='application/json', max_length=50),
        ),
    ]
