# Generated by Django 5.2.6 on 2025-10-05 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0002_apiendpoint_body_template_apiendpoint_content_type'),
        ('databases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('transformation_code', models.CharField(max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_table', models.CharField(max_length=255)),
                ('field_mappings', models.JSONField(default=list)),
                ('update_on_conflict', models.BooleanField(default=False)),
                ('conflict_columns', models.JSONField(default=list)),
                ('batch_size', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('api_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='apis.apiendpoint')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='databases.databaseconnection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='MappingExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='mappings.datamapping')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
